[package]
name = "markdown-extract"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
comrak = "0.48.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
chrono = "0.4.38"
chrono-tz = "0.10.0"
grep-regex = "0.1.14"
grep-searcher = "0.1.14"
ignore = "0.4.23"
once_cell = "1.19.0"

[build-dependencies]
serde_json = "1.0.145"
